# fly.toml app configuration file generated for patterns-matter on 2025-07-28T11:37:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'patterns-matter'
primary_region = 'ams'

[checks]
  [checks.web]
    grace_period = "10s"
    interval = "15s"
    method = "get"
    path = "/"
    timeout = "2s"
    type = "http"


[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
source = "datavol"
destination = "/data"
